name: train

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
    - mlflow>=1.0
    - pandas==2.1.0
    - numpy==1.25.2
    - scikit-learn==1.2.2
    - xgboost==1.7.6
    - optuna==3.3.0